image: node:10

cache:
    paths:
        - node_modules/
        - .yarn/
        - .firebase/

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - yarn global add firebase-tools hexo-cli --cache-folder .yarn
    - yarn install --cache-folder .yarn

pages:
    script:
        - hexo generate
        - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID @ Hash ${CI_COMMIT_SHA:0:7}" --token $FIREBASE_TOKEN --non-interactive
    artifacts:
        paths:
            - public
    only:
        - master
