image: node:latest

cache:
    paths:
        - node_modules/
        - .firebase/

variables:
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
    - npm install -g firebase-tools@4.2.1 hexo-cli
    - npm install

pages:
    script:
        - hexo generate
        - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID @ Hash ${CI_COMMIT_SHA:0:7}" --token $FIREBASE_TOKEN
    artifacts:
        paths:
            - public
    only:
        - master
