language: node_js
node_js:
  - "lts/*"

branches:
  only:
  - source

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - sed -i "s/http:\/\/registry.npm.taobao.org/https:\/\/registry.npmjs.org/g" yarn.lock

install:
  - yarn

script:
  - yarn build

deploy:
  - provider: firebase
    skip-cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    message: $TRAVIS_COMMIT_MESSAGE
    on:
      branch: source
  - provider: pages
    skip_cleanup: true
    target-branch: master
    github_token: $GITHUB_TOKEN
    local_dir: public
    on:
      branch: source

after_deploy:
  - hexo clean
  - hexo algolia
