language: node_js
node_js:
  - "lts/*"

branches:
  only:
  - source

cache:
  yarn: true
  directories:
    - node_modules

# before_install:
#   - sed -i "s/http:\/\/registry.npm.taobao.org/https:\/\/registry.yarnpkg.com/g" yarn.lock

install:
  - yarn

script:
  - yarn build

deploy:
  - provider: firebase
    skip-cleanup: true
    token:
      secure: $FIREBASE_TOKEN
    message: $TRAVIS_COMMIT_MESSAGE
    on:
      branch: source

after_deploy:
  - hexo clean
  - hexo algolia
